
include:

  ### CORNE START ###
    ### nice_oled START ###
    # nice_nano_v2 + nice_oled
  - board: nice_nano_v2
    shield: corne_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Corne_Oled\"
    artifact-name: nice_corne_left_oled
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corne_right nice_oled
    artifact-name: nice_corne_right_oled

    # peripheral_left + nice_nano_v2 + nice_oled
  - board: nice_nano_v2
    shield: corne_left_peripheral nice_oled
    artifact-name: nice_corne_left_peripheral_oled
    ### nice_oled END ###

    ### ProMicro_Dongle START ###
    # nice_nano_v2 dongle
  - board: nice_nano_v2
    shield: corne_dongle_pro_micro
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle\"
    artifact-name: nice_corne_dongle_pro_micro
    snippet: studio-rpc-usb-uart
    # snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: corne_dongle_pro_micro dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle_O\"
    artifact-name: nice_corne_dongle_oled
    snippet: studio-rpc-usb-uart
    # snippet: zmk-usb-logging
    ### Pro Micro END ###
  ### CORNE END ###

  ### SETTINGS_RESET START ###
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset
  ### SETTINGS_RESET END ###
